/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RED */
#define RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_0_INBUF_ENABLED 0u
#define RED_0_INIT_DRIVESTATE 1u
#define RED_0_INIT_MUXSEL 0u
#define RED_0_INPUT_SYNC 2u
#define RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_0_NUM 3u
#define RED_0_PORT GPIO_PRT0
#define RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_INBUF_ENABLED 0u
#define RED_INIT_DRIVESTATE 1u
#define RED_INIT_MUXSEL 0u
#define RED_INPUT_SYNC 2u
#define RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_NUM 3u
#define RED_PORT GPIO_PRT0
#define RED_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* BLUE */
#define BLUE_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLUE_0_INBUF_ENABLED 0u
#define BLUE_0_INIT_DRIVESTATE 1u
#define BLUE_0_INIT_MUXSEL 0u
#define BLUE_0_INPUT_SYNC 2u
#define BLUE_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLUE_0_NUM 1u
#define BLUE_0_PORT GPIO_PRT11
#define BLUE_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BLUE_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BLUE_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLUE_INBUF_ENABLED 0u
#define BLUE_INIT_DRIVESTATE 1u
#define BLUE_INIT_MUXSEL 0u
#define BLUE_INPUT_SYNC 2u
#define BLUE_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLUE_NUM 1u
#define BLUE_PORT GPIO_PRT11
#define BLUE_SLEWRATE CY_GPIO_SLEW_FAST
#define BLUE_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Avoice */
#define Avoice_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Avoice_0_INBUF_ENABLED 0u
#define Avoice_0_INIT_DRIVESTATE 1u
#define Avoice_0_INIT_MUXSEL 0u
#define Avoice_0_INPUT_SYNC 2u
#define Avoice_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Avoice_0_NUM 0u
#define Avoice_0_PORT GPIO_PRT10
#define Avoice_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Avoice_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Avoice_DRIVEMODE CY_GPIO_DM_ANALOG
#define Avoice_INBUF_ENABLED 0u
#define Avoice_INIT_DRIVESTATE 1u
#define Avoice_INIT_MUXSEL 0u
#define Avoice_INPUT_SYNC 2u
#define Avoice_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Avoice_NUM 0u
#define Avoice_PORT GPIO_PRT10
#define Avoice_SLEWRATE CY_GPIO_SLEW_FAST
#define Avoice_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* VoiceOut */
#define VoiceOut_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VoiceOut_0_INBUF_ENABLED 0u
#define VoiceOut_0_INIT_DRIVESTATE 1u
#define VoiceOut_0_INIT_MUXSEL 0u
#define VoiceOut_0_INPUT_SYNC 2u
#define VoiceOut_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VoiceOut_0_NUM 6u
#define VoiceOut_0_PORT GPIO_PRT9
#define VoiceOut_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VoiceOut_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VoiceOut_DRIVEMODE CY_GPIO_DM_ANALOG
#define VoiceOut_INBUF_ENABLED 0u
#define VoiceOut_INIT_DRIVESTATE 1u
#define VoiceOut_INIT_MUXSEL 0u
#define VoiceOut_INPUT_SYNC 2u
#define VoiceOut_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VoiceOut_NUM 6u
#define VoiceOut_PORT GPIO_PRT9
#define VoiceOut_SLEWRATE CY_GPIO_SLEW_FAST
#define VoiceOut_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Rx */
#define CapSense_Rx_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Rx_0_INBUF_ENABLED 0u
#define CapSense_Rx_0_INIT_DRIVESTATE 1u
#define CapSense_Rx_0_INIT_MUXSEL 4u
#define CapSense_Rx_0_INPUT_SYNC 2u
#define CapSense_Rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Rx_0_NUM 1u
#define CapSense_Rx_0_PORT GPIO_PRT8
#define CapSense_Rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Rx_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Rx_1_INBUF_ENABLED 0u
#define CapSense_Rx_1_INIT_DRIVESTATE 1u
#define CapSense_Rx_1_INIT_MUXSEL 4u
#define CapSense_Rx_1_INPUT_SYNC 2u
#define CapSense_Rx_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Rx_1_NUM 2u
#define CapSense_Rx_1_PORT GPIO_PRT8
#define CapSense_Rx_1_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Rx_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Tx */
#define CapSense_Tx_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Tx_0_INBUF_ENABLED 0u
#define CapSense_Tx_0_INIT_DRIVESTATE 1u
#define CapSense_Tx_0_INIT_MUXSEL 0u
#define CapSense_Tx_0_INPUT_SYNC 2u
#define CapSense_Tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Tx_0_NUM 0u
#define CapSense_Tx_0_PORT GPIO_PRT1
#define CapSense_Tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Tx_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Tx_INBUF_ENABLED 0u
#define CapSense_Tx_INIT_DRIVESTATE 1u
#define CapSense_Tx_INIT_MUXSEL 0u
#define CapSense_Tx_INPUT_SYNC 2u
#define CapSense_Tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Tx_NUM 0u
#define CapSense_Tx_PORT GPIO_PRT1
#define CapSense_Tx_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_CintA */
#define CapSense_CintA_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintA_0_INBUF_ENABLED 0u
#define CapSense_CintA_0_INIT_DRIVESTATE 1u
#define CapSense_CintA_0_INIT_MUXSEL 0u
#define CapSense_CintA_0_INPUT_SYNC 2u
#define CapSense_CintA_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintA_0_NUM 1u
#define CapSense_CintA_0_PORT GPIO_PRT7
#define CapSense_CintA_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintA_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_CintA_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintA_INBUF_ENABLED 0u
#define CapSense_CintA_INIT_DRIVESTATE 1u
#define CapSense_CintA_INIT_MUXSEL 0u
#define CapSense_CintA_INPUT_SYNC 2u
#define CapSense_CintA_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintA_NUM 1u
#define CapSense_CintA_PORT GPIO_PRT7
#define CapSense_CintA_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintA_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_CintB */
#define CapSense_CintB_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintB_0_INBUF_ENABLED 0u
#define CapSense_CintB_0_INIT_DRIVESTATE 1u
#define CapSense_CintB_0_INIT_MUXSEL 0u
#define CapSense_CintB_0_INPUT_SYNC 2u
#define CapSense_CintB_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintB_0_NUM 2u
#define CapSense_CintB_0_PORT GPIO_PRT7
#define CapSense_CintB_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintB_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_CintB_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintB_INBUF_ENABLED 0u
#define CapSense_CintB_INIT_DRIVESTATE 1u
#define CapSense_CintB_INIT_MUXSEL 0u
#define CapSense_CintB_INPUT_SYNC 2u
#define CapSense_CintB_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintB_NUM 2u
#define CapSense_CintB_PORT GPIO_PRT7
#define CapSense_CintB_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintB_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
